
import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/form.module.css'; // Import the CSS module
import { signOut} from 'next-auth/react'

export default function Home() {

  const [submitting, setSubmitting] = useState(false);

  async function handleOnSubmit(e) {
            e.preventDefault();
            setSubmitting(true);
            const formData = new FormData(e.currentTarget);
        
            Array.from(e.currentTarget.elements).forEach(field => {
              if ( !field.name ) return;
              if (field.type === 'radio' && !field.checked) return;
              formData[field.name] = field.value;
            });
        
            try {
             
              const response = await fetch('/api/connection', {
                method: 'POST',
                body: JSON.stringify(formData),
                headers: {
                  'Content-Type': 'application/json',
                },
                // method: 'POST',
                // body: formData,
              });

              const data = await response.json();
              console.log(data);
        
              if (response.ok) {
                alert('Form submitted successfully');
              } else {
                alert('An error occurred while sending the email');
              }
            } catch (error) {
              console.error(error);
              alert('An error occurred while sending the email');
            } finally {
              setSubmitting(false);
            }
          }
        

  return (
    <>
      <Head>
        <title>BIITS IT SUPPORT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


  <div className={styles['form-container']}> {/* Apply the CSS class to the form container */}
    <form  onSubmit={handleOnSubmit}>
               
                    <center><label htmlFor="fname"> IT SUPPORT ISSUE DETAILS</label></center><br></br>
                
                    <button type="submit" className={styles['submit-button']} onClick={()=>signOut({callbackUrl: 'http://localhost:3000'})}>signOut</button><br></br>
                    <br></br>
                <p>
                    <label htmlFor="fname">FIRST NAME</label>
                    <input type="text" id="fname" placeholder="Enter First Name..." name="fname"></input>
                </p>
                <p>
                    <label htmlFor="lname">LAST NAME</label>
                    <input type="text" id="lname" placeholder="Enter Last Name..."name="lname"></input>
                </p>
                <p>
                    <label htmlFor="email">EMAIL</label>
                    <input type="email" id="email" placeholder="Enter the Email..." name="email"></input>
                </p>
                <p>
                    <label htmlFor="phone">PHONE NUMBER</label>
                    <input type="text" id="phone" placeholder="Enter Phone Number..." name="phone"></input>
                </p>
                <p>
                    <label htmlFor="place">PLACE WHERE THE ISSUE OCCURED</label>
                    <input type="radio" name="place" value="Inside BIITS" id="place1" />
                    <label htmlFor="inside-biits">Inside BIITS</label>
                    <input type="radio" name="place" value="Outside BIITS" id="place2" />
                    <label htmlFor="outside-biits">Outside BIITS</label>
               </p>
            
               <p>
                    <label htmlFor="date">PLEASE SELECT THE DATE OF ISSUE HAPPENED</label>
                    <input type="date" id="date" name="date" />
               </p>

               <p>
                    <label htmlFor="priority">ISSUE PRIORITY</label>
                    <input type="radio" name="priority"  value="High" id="high" />
                    <label htmlFor="high">High</label>
                    <input type="radio" name="priority" id="moderate" value="Moderate" />
                    <label htmlFor="moderate">Moderate</label>
                    <input type="radio" name="priority" id="low" value="Low" />
                    <label htmlFor="low">Low</label>
               </p>
               <p>
                    <label htmlFor="issue">PLEASE SELECT THE ISSUE DETAILS</label>
                    <input type="radio" name="issue" id="system-issue" value="System Issue" />
                    <label htmlFor="system-issue">System Issue</label>                   
                    <input type="radio" name="issue" id="software-issue" value="Software Issue" />
                    <label htmlFor="software-issue">Software Issue</label>
                    <input type='radio' name='issue' id='others' value="Others"/>
                    <label htmlFor='others'>Others</label>
               </p>
                <p>
                    <label htmlFor="img">IF YOU HAVE FILES RELATING TO THIS ISSUE, YOU CAN UPLOAD THEM HERE</label>
                    <input type="file" id="image" name="img" />
                </p>
                
                <button type="submit" disabled={submitting} className={styles['submit-button']}>{submitting ? 'Submitting...' : 'Submit'}</button>

    </form>
    </div>

    </>
  )
}
